In [6]:
from CNF_Creator import *

In [2]:
import numpy as np

In [11]:
cnfc = CNF_Creator(n=50)
# sentence = cnfc.ReadCNFfromCSVfile()
sentence = cnfc.CreateRandomSentence(m=120)
print(type(sentence))

<class 'list'>


In [13]:
print(type(sentence[0]))

<class 'list'>


In [15]:
print(type(sentence[0][0]))
print(len(sentence[0]))

<class 'int'>
3


In [17]:
sat = 20
m = 3
val = sat/m
print(val)

6.666666666666667


In [26]:
arr = np.array([0,1,2,3,4,5])
for i in range(len(arr)-1):
    print(arr[i], end=", ")
print(arr[len(arr)-1])

0, 1, 2, 3, 4, 5


In [14]:
narr = np.array([[0,1,2],[3,4,5]])
child = np.array([[6,7,8]])
print(narr)
narr = np.append(narr, child, axis=0)
print(narr)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
arr = np.array([1,2,3,4])
arr = np.append(arr, 5)
print(arr)

[1 2 3 4 5]


In [17]:
arr = np.array([[0,1,2],[3,4,5]])
child = np.array([6,7,8])
arr = np.insert(arr, 2 ,child, axis=0)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
