In [1]:
from CNF_Creator import *

In [1]:
import numpy as np

In [2]:
cnfc = CNF_Creator(n=50)
# sentence = cnfc.ReadCNFfromCSVfile()
sentence = cnfc.CreateRandomSentence(m=120)
print(type(sentence))
print('Random sentence : ',sentence)

<class 'list'>
Random sentence :  [[-50, -41, -9], [-50, -41, 8], [-49, -38, -6], [-49, -37, -10], [-49, -29, -8], [-49, 10, 40], [-48, -38, 12], [-48, -18, 23], [-48, 35, 45], [-47, -27, 39], [-47, -13, -11], [-46, -38, -25], [-46, -15, 22], [-46, 35, 42], [-46, 45, 47], [-45, -43, 33], [-45, -33, 9], [-45, -30, 34], [-45, -28, -24], [-45, -25, 36], [-44, -38, 24], [-44, -31, -10], [-44, -21, 27], [-44, 6, 17], [-44, 15, 43], [-43, -31, -29], [-43, -12, 38], [-43, -2, 20], [-43, 28, 45], [-42, 1, 36], [-41, -31, -26], [-41, -24, -22], [-41, -20, 13], [-40, -39, 29], [-40, -38, 24], [-40, -30, -28], [-40, -29, 4], [-40, 17, 45], [-40, 20, 37], [-40, 24, 43], [-39, -6, 35], [-39, -2, 40], [-39, 41, 43], [-37, -31, -1], [-37, -14, 17], [-37, 4, 49], [-36, -33, 6], [-36, -33, 7], [-36, -6, 19], [-35, -19, -3], [-35, 25, 49], [-34, -20, -15], [-33, -13, 23], [-33, -5, 16], [-32, -23, 46], [-32, -1, 41], [-32, 33, 34], [-31, -24, 7], [-31, -24, 27], [-31, -17, -12], [-31, 11, 16], [-31, 11,

In [ ]:
print(type(sentence[0]))

In [ ]:
print(type(sentence[0][0]))
print(len(sentence[0]))

In [ ]:
sat = 20
m = 3
val = sat/m
print(val)

In [ ]:
arr = np.array([0,1,2,3,4,5])
for i in range(len(arr)-1):
    print(arr[i], end=", ")
print(arr[len(arr)-1])

In [ ]:
narr = np.array([[0,1,2],[3,4,5]])
child = np.array([[6,7,8]])
print(narr)
narr = np.append(narr, child, axis=0)
print(narr)

In [ ]:
arr = np.array([1,2,3,4])
arr = np.append(arr, 5)
print(arr)

In [ ]:
arr = np.array([[0,1,2],[3,4,5]])
child = np.array([6,7,8])
arr = np.insert(arr, 2 ,child, axis=0)
print(arr)

In [ ]:
xarr = np.array([0,1,2,3,4,5,6,7,8,9])
yarr = np.array([10,11,12,13,14,15,16,17,18,19])

n = randint(0,len(xarr)-1)
print(n)
o = randint(0,1)
print(o)
# append beginning substring of one to ending one of another
if(o==1):
    xtemp = xarr[:n]
    ytemp = yarr[n:]
    print(type(xtemp))
else:
    xtemp = yarr[:n]
    ytemp = xarr[n:]
    print(type(xtemp))
child = np.concatenate((xtemp, ytemp))
print(child)

In [2]:
from random import randint
from random import sample

In [2]:
import threading, os, time

In [3]:
theVar = 1

class MyThread ( threading.Thread ):

   def run (self):

      global theVar
      print ("This is thread" + str ( theVar ) + "speaking.")
      print ("Hello and good bye.")
      theVar = theVar + 1
      if theVar == 4:
          #sys.exit(1)
          os._exit(1)
      print( "(done)")

for x in range (7):
   MyThread().start()

In [12]:
n=15
ones = np.ones(n, dtype=int)
narr = []
while len(narr)<10:
    c = randint(1,n)
    ind = sample(range(1,n), c)
    arr = ones.copy()
    for j in ind:
        arr[j] = -1
    uni = True
    for j in range(len(narr)):
        if(np.array_equal(narr[j], arr)):
            uni = False
            break
    if(uni==True):
        narr.append(arr)
for a in narr:
    print(a)

[ 1  1  1 -1  1  1 -1  1  1  1 -1  1  1 -1  1]
[ 1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1]
[ 1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1]
[ 1  1 -1  1 -1 -1 -1 -1  1 -1 -1  1 -1  1 -1]
[ 1  1 -1 -1 -1  1 -1 -1  1  1  1  1 -1  1  1]
[ 1  1  1 -1  1  1  1  1  1  1  1  1  1 -1  1]
[ 1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1]
[ 1  1  1  1 -1  1  1 -1  1  1 -1 -1  1  1  1]
[ 1 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
[ 1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1 -1 -1]


In [7]:
def fitness_func(sentence, model):
    sat = 0
    m = len(sentence)
    for i in range(m):
        for j in range(3):
            if sentence[i][j] * model[abs(sentence[i][j])-1] > 0:
                sat += 1
                break
    val = (sat/m)*100
    return val

In [8]:
def mutate(child):
    ind = randint(0,len(child)-1)
    child[ind]*=-1
    return child

In [6]:
def reproduce(xarr, yarr):
    n = randint(0,len(xarr)-1)
    o = randint(0,1)
    # append beginning substring of one to ending one of another
    if(o==1):
        xtemp = xarr[:n]
        ytemp = yarr[n:]
    else:
        xtemp = yarr[:n]
        ytemp = xarr[n:]
    child = np.concatenate((xtemp, ytemp))

    # with some random prob (1 in 10), mutate child
    prob = randint(0,9)
    if prob==0:
        child = mutate(child)

    return child

In [17]:
def randomGenerate(n):
    ones = np.ones(n, dtype=int)
    narr = []
    while len(narr)<20:
        c = randint(0,n)
        ind = sample(range(n-1), c)
        arr = ones.copy()
        for j in ind:
            arr[j] = -1
        # append if new one is unique
        uni = True
        for j in range(len(narr)):
            if(np.array_equal(narr[j], arr)):
                uni = False
                break
        if(uni==True):
            narr.append(arr)
    return narr

In [21]:
def gen_algo_basic(sentence):
    narr = []
    opt_sol = np.empty(50, dtype = int)
    fitness = np.empty(50, dtype = float)
    stagfact = 0
    # TODO: generate first 20 different random states in narr
    narr = randomGenerate(50)
    n=0 # number of iterations. To be used in code to check stagnation
    while True:
        # newnarr = np.empty(dtype = int)
        newnarr = []
        best_fit = np.empty(50, dtype = int)
        for i in range(20):
            # print(i)
            x = randint(0,len(narr)-1)
            y = randint(0,len(narr)-1)
            while y==x:
                y = randint(0,len(narr)-1)
            child = reproduce(narr[x],narr[y])
            # append child to newnarr
            # temp = len(newnarr)
            # newnarr = np.insert(newnarr, temp, child, axis=0)
            newnarr.append(child)
        narr = newnarr.copy()
        
        for i in range(len(narr)):
            if(fitness_func(sentence, narr[i]) == 100 ):
                return narr[i]
            if(fitness_func(sentence, narr[i]) > fitness_func(sentence, best_fit)):
                best_fit = narr[i].copy()
        if(fitness_func(sentence, best_fit) > fitness_func(sentence, opt_sol)):
            opt_sol = best_fit.copy()
        n+=1
        n%=50
        # check if algo has stagnated
        if fitness_func(sentence, best_fit)-fitness[n] <= 5: #difference in current fitness and fitness 50 iterations ago
            if stagfact >=50: # stagnant for past 50 iterations (assumed stagnated)
                break
            else: # stagnated for a while but not enough to assign stagnated
                fitness[n] = fitness_func(sentence, best_fit)
                stagfact += 1
        else:
            fitness[n] = fitness_func(sentence, best_fit)
            stagfact = max(0, stagfact-10) # decrease stagnation factor to give more time to stagnate
    
    max_fitness = fitness_func(sentence, opt_sol)
    for i in range(50):
        opt_sol[i]*=(i+1)
    print(opt_sol)
    print(max_fitness)
    return opt_sol

In [22]:
arr = gen_algo_basic(sentence)

[ -1  -2  -3   4   5   6   7   8  -9  10  11  12 -13 -14 -15  16  17  18
  19  20  21  22  23  24  25  26 -27 -28  29  30 -31  32  33  34  35  36
 -37  38 -39 -40 -41 -42  43 -44  45  46 -47  48  49  50]
94.16666666666667


In [16]:
list1 = range(10)
print(list1)

range(0, 10)


In [1]:
def fitness(arr):
    n = len(arr)
    sum=0
    for i in arr:
        sum+=i
    fvalue = sum/n
    return fvalue

In [7]:
arrlist = []
for i in range(5):
    temp = sample(range(20), 10)
    temp = sorted(temp)
    arr = np.array(temp)
    arrlist.append(arr)
    print(arr)

print(type(arrlist[0]))


[ 2  3  6  9 12 13 14 15 17 18]
[ 1  2  3  9 10 11 12 13 15 18]
[ 0  1  2  4  9 12 13 14 15 17]
[ 0  1  2  3  5 10 11 13 18 19]
[ 1  3  5  6  7  9 10 14 16 18]
<class 'numpy.ndarray'>


In [16]:
sortedlist = sorted(arrlist, key=fitness, reverse=True)
for i in range(5):
    print(sortedlist[i], fitness(sortedlist[i]))

[ 2  3  6  9 12 13 14 15 17 18] 10.9
[ 1  2  3  9 10 11 12 13 15 18] 9.4
[ 1  3  5  6  7  9 10 14 16 18] 8.9
[ 0  1  2  4  9 12 13 14 15 17] 8.7
[ 0  1  2  3  5 10 11 13 18 19] 8.2


In [12]:
trunclist= sortedlist[:3]
for i in range(len(trunclist)):
    print(trunclist[i])

[ 2  3  6  9 12 13 14 15 17 18]
[ 1  2  3  9 10 11 12 13 15 18]
[ 1  3  5  6  7  9 10 14 16 18]


In [1]:
import numpy as np
import time, threading, os

In [6]:
testarr = np.array([1,2,3,4,5,6])

def threadfunc():
    testarr[1] = 45
    tb = time.perf_counter()
    time.sleep(5)
    print("sidethread", testarr)
    tend = time.perf_counter() - tb
    print(tend)
    print("sidethread exiting")
    # os._exit(2)

def mainfunc():
    t1 = threading.Thread(target=threadfunc)
    t1.start()
    testarr[1] = 34
    t1.join()
    print("mainthread ", testarr)
    time.sleep(6)
    print("mainthread exiting")
    # os._exit(1)

In [7]:
mainfunc()

sidethread [ 1 34  3  4  5  6]
5.019032699999997
sidethread exiting
mainthread  [ 1 34  3  4  5  6]
mainthread exiting


In [2]:
import multiprocessing as mp

In [5]:
result = mp.Array('i', 4)
for i in range(4):
    result[i]=i*i
print(type(result))
print(result)

newresult = np.array(result)
print(type(newresult))
print(newresult)

<class 'multiprocessing.sharedctypes.SynchronizedArray'>
<SynchronizedArray wrapper for <multiprocessing.sharedctypes.c_long_Array_4 object at 0x000001743028A0C8>>
<class 'numpy.ndarray'>
[0 1 4 9]
