In [ ]:
from CNF_Creator import *

In [1]:
import numpy as np

In [ ]:
cnfc = CNF_Creator(n=50)
# sentence = cnfc.ReadCNFfromCSVfile()
sentence = cnfc.CreateRandomSentence(m=120)
print(type(sentence))

In [ ]:
print(type(sentence[0]))

In [ ]:
print(type(sentence[0][0]))
print(len(sentence[0]))

In [ ]:
sat = 20
m = 3
val = sat/m
print(val)

In [ ]:
arr = np.array([0,1,2,3,4,5])
for i in range(len(arr)-1):
    print(arr[i], end=", ")
print(arr[len(arr)-1])

In [ ]:
narr = np.array([[0,1,2],[3,4,5]])
child = np.array([[6,7,8]])
print(narr)
narr = np.append(narr, child, axis=0)
print(narr)

In [ ]:
arr = np.array([1,2,3,4])
arr = np.append(arr, 5)
print(arr)

In [ ]:
arr = np.array([[0,1,2],[3,4,5]])
child = np.array([6,7,8])
arr = np.insert(arr, 2 ,child, axis=0)
print(arr)

In [ ]:
xarr = np.array([0,1,2,3,4,5,6,7,8,9])
yarr = np.array([10,11,12,13,14,15,16,17,18,19])

n = randint(0,len(xarr)-1)
print(n)
o = randint(0,1)
print(o)
# append beginning substring of one to ending one of another
if(o==1):
    xtemp = xarr[:n]
    ytemp = yarr[n:]
    print(type(xtemp))
else:
    xtemp = yarr[:n]
    ytemp = xarr[n:]
    print(type(xtemp))
child = np.concatenate((xtemp, ytemp))
print(child)

In [7]:
from random import randint
from random import sample

In [1]:
import threading, sys, os

In [3]:
theVar = 1

class MyThread ( threading.Thread ):

   def run (self):

      global theVar
      print ("This is thread" + str ( theVar ) + "speaking.")
      print ("Hello and good bye.")
      theVar = theVar + 1
      if theVar == 4:
          #sys.exit(1)
          os._exit(1)
      print( "(done)")

for x in range (7):
   MyThread().start()

In [12]:
n=15
ones = np.ones(n, dtype=int)
narr = []
while len(narr)<10:
    c = randint(1,n)
    ind = sample(range(1,n), c)
    arr = ones.copy()
    for j in ind:
        arr[j] = -1
    uni = True
    for j in range(len(narr)):
        if(np.array_equal(narr[j], arr)):
            uni = False
            break
    if(uni==True):
        narr.append(arr)
for a in narr:
    print(a)

[ 1  1  1 -1  1  1 -1  1  1  1 -1  1  1 -1  1]
[ 1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1]
[ 1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1]
[ 1  1 -1  1 -1 -1 -1 -1  1 -1 -1  1 -1  1 -1]
[ 1  1 -1 -1 -1  1 -1 -1  1  1  1  1 -1  1  1]
[ 1  1  1 -1  1  1  1  1  1  1  1  1  1 -1  1]
[ 1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1]
[ 1  1  1  1 -1  1  1 -1  1  1 -1 -1  1  1  1]
[ 1 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
[ 1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1 -1 -1]
